name: polo_server
description: A WebSocket Library written in Pure Dart.
repository: https://github.com/AyushChothe/polo
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
