name: polo_client
description: A WebSocket Library written in Pure Dart. Easy API for writing WebSocket based Apps or Games. Also Support for Flutter and Web.
repository: https://github.com/AyushChothe/polo
version: 0.0.3
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.0 <3.0.0"

# dependencies:
# uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
